### ISSUE TITLE
Multi-line Fragment Selectors Not Recognized

### ISSUE THREAD

**Issue by iansedano** [sgruendel/vscode-extension-thymeleaf-navigate#1]
Very nice extension! I'm glad this kind of thing is coming to VS Code, thank you for your efforts!

I often use multi-line fragment selectors for readability:

```html
<li
  th:replace="~{components/outcome-bullet :: outcome(
    heading = 'Lorem Ipsum',
    text = ${descriptionText}
  )}"
></li>
```

However, it seems like the extension doesn't pick these up. I've tried reopening the files, and reopening the file where the fragment is defined, but no luck.

If I had to guess it's probably a regex matching side-effect (maybe it's looking for the closing `}"` or something similar), but having just discovered the extension, I can't say for sure. I just thought it would be good to start the conversation here.

I'm running VS Code `v.1.85.1` on Fedora Linux 39, with `v1.2.0` of the extension.

**Comment by sgruendel** [comment]
Thanks Ian, nice dog there :)  You're right, regex currently only works for one line expressions, will look into it next weekend.

**Comment by iansedano** [comment]
That's working great, thanks @sgruendel!
